/// <reference types="astro/client" />
/// <reference types="@cloudflare/workers-types" />

// Define KV namespace type
type KVNamespace = import("@cloudflare/workers-types").KVNamespace;

// Define our custom environment with bindings
interface Env {
  // KV namespaces
  POSTS_KV: KVNamespace;
  GENERATION_COUNTER_KV: KVNamespace;
  
  // Environment variables
  OPENAI_API_KEY: string;
  DAILY_GENERATION_LIMIT: string;
  ALLOW_USER_GENERATIONS: string;
}

// Define Cloudflare runtime with our environment
type Runtime = import("@astrojs/cloudflare").Runtime<Env>;

// Extend Astro's environment definitions
declare namespace App {
  interface Locals extends Runtime {
    // Additional runtime properties can be added here
  }
}

// Define post data structure
interface Post {
  title: string;       // "What X taught me about Y"
  content: string;     // The generated post content
  xId: string;         // ID of the X value
  yId: string;         // ID of the Y value
  createdAt: number;   // Timestamp
  isGenerated: boolean; // Whether it was generated by AI or pre-written
}

// Define X value structure
interface XValue {
  id: string;
  activity: string;
  emoji: string;
  categories: string[];
}

// Define Y value structure
interface YValue {
  id: string;
  concept: string;
  emoji: string;
  categories: string[];
} 